project: default
source:
  repoURL: https://github.com/djordjevic-milan/sample-task.git
  path: helm
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: react-app
