apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: react-app
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
    # Init container will remove data from database! Use for cleen boot and edit MYSQL_INITDB_SKIP_TZINFO variable in MySQL configmap.
      # initContainers:
      #   - name: mysql-storage-cleanup
      #     image: busybox
      #     command:
      #       - "sh"
      #       - "-c"
      #       - "rm -rf /var/lib/mysql/*"
      #     volumeMounts:
      #       - name: mysql-storage
      #         mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_INITDB_SKIP_TZINFO
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_INITDB_SKIP_TZINFO
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
