{{- range .Values.services }}
{{- if .secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- range .secret }}
  {{ .key }}: {{ .value | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
