commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - sampletask-k8s/sampletask-deployment.yml
  - sampletask-k8s/sampletask-service.yml
  - sampletask-k8s/sampletask-mysql.yml
  # service discovery eureka/consul
  - registry-k8s/consul.yml
  - registry-k8s/consul-config-loader.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
