apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: sampletask
      context: ../myApp2
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
