{{- range .Values.services }}
  {{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ .name }}
    spec:
      containers:
        - name: {{ $.Release.Name }}-{{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          env:
            {{- range .env }}
              {{- if .value }}
            - name: {{ .name }}
              value: {{ .value | quote }}
              {{- else if .key }}
            - name: {{ .key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-{{ .name }}-config
                  key: {{ .key }}
              {{- end }}
            {{- end }}
            {{- range .secret }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-{{ .name }}-secret  # This is where the secret name is constructed
                  key: {{ .key }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .probes.readiness.httpGet.path }}
              port: {{ .probes.readiness.httpGet.port }}
            initialDelaySeconds: {{ .probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .probes.readiness.periodSeconds }}
            failureThreshold: {{ .probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .probes.liveness.httpGet.path }}
              port: {{ .probes.liveness.httpGet.port }}
            initialDelaySeconds: {{ .probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .probes.liveness.periodSeconds }}
            failureThreshold: {{ .probes.liveness.failureThreshold }}
---
  {{- end }}
{{- end }}
