apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: react-app
type: Opaque
data:
  mysql-root-password: cGFzczEyMw==
  mysql-user: YXBwdXNlcg==
  mysql-password: cGFzczEyMw==
  mysql-database: YXBwZGI=
