configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODQxY2VjNmQzNGE4YzcyYTE5YjFmY2U0YzcyOTY3MTRjNGJlMmFiMzI2MWZlNzZhMzJlZjJjZTIxMTkzZDQyYzhiYzhiNjAxMzc1MjJjYjUxN2EzZDllOTAzODYxZWMwZTRmMmU5NTczMmUwY2FmZGU0N2MyNmIxOTYwOWQ4ZjE=
