app:
  name: react-app

ingress:
  enabled: true
  host: react-app.local
  tls: true
  tlsSecret: react-app-tls
  tlsCrt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaVENDQWsyZ0F3SUJBZ0lVZUo4dE1peTE4ZWJjZ1pMUFYzYTd0QkZFZXc0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd05ERVlNQllHQTFVRUF3d1BjbVZoWTNRdFlYQndMbXh2WTJGc01SZ3dGZ1lEVlFRS0RBOXlaV0ZqZEMxaApjSEF1Ykc5allXd3dIaGNOTWpVd05ETXdNVGcwT0RJeFdoY05Nall3TkRNd01UZzBPREl4V2pBME1SZ3dGZ1lEClZRUUREQTl5WldGamRDMWhjSEF1Ykc5allXd3hHREFXQmdOVkJBb01EM0psWVdOMExXRndjQzVzYjJOaGJEQ0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNK0hkOXhpMmNJMTdBeWFZemNwbU1OcgpKQ0FUeXpqRjFPenhwR1pXeGRsaEFkdjhNUUwrUE8xekJRcFZKcjBjWHlZREdrOUsvTEFIWHpCZ3FDemw2R3RwCld5OXVZUERYVnA3UGtCcXM3dkxHTmlCVXRLcXZlMFhyNXpYbnF2UkY3RERGTEwyNllzcEZ4R3oyem5VU0FyTmIKZ1grYjlsZ1AvUU0va2FrckVSL2hEVjIwT05iTUgyWFBFSkV0YU1wVFRNL01XSnFtNU9WRE5iUisvU0ZQbUl0RQorNlc3K2tlZTNFSGJnZVRLc1FnTjhJVEgySkdLMmV0MnpRVXo1SGFNbGdMQkVQaFd6NUVHQkFEM0FKb29MNlYxCk8wc2FZMHFVUkNJMGN0ZHl4bTFnY1FjNGt0QzJRcUhCU1FvRG4wTVZkb2pGWUc5K1dTak5zWFVYTkhZZXJNc0MKQXdFQUFhTnZNRzB3SFFZRFZSME9CQllFRk9nWmw2RFhxZlJrNTNBem5hbTBpLzY2U2grdE1COEdBMVVkSXdRWQpNQmFBRk9nWmw2RFhxZlJrNTNBem5hbTBpLzY2U2grdE1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0dnWURWUjBSCkJCTXdFWUlQY21WaFkzUXRZWEJ3TG14dlkyRnNNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNVRUJSWElzbDcKSmpCdlVjSlFJSFRGM0RLUzFaT0g4cEVycjVxMFVYaWREbjVRcm5CRDN2T1poNTEyajZiTUdqZzZuYmFibFBMegp4dmhqcjdrUndtZzNhc1AyNjJ3YTcvNUNtVndJRWxHZGpqdGRTVXFxSVlKRVk2UWNWWEhwUllyU2ZZYkVLSWZBCjZZRFBBTnZHdTEwaHZKM1ZuZURsTkNVM3hpSk85enF5aldYS0RrY0JqbmdnNFJYdkVPd2VtRi9kMnd6VlV4cTYKbnBERzhzYmdaNWJyVkFQcDFXQU5naWtQUjRDZjZMQ0J0b0YwN1U4cXRqNDNvZjFIQVpaMnRmWWRSOVhVTi90QwowcVQ4S0Z6Q0sxeFAyRmJWS0wwaHcrUWhDSkpYQXg3K3NXZUJWREVvUEp5S01kc3E2Y3RHZzVCUzNxV0o3dVJoCk5VS0VIbWRsQm0zZAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tlsKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFBoM2ZjWXRuQ05ld00KbW1NM0taakRheVFnRThzNHhkVHM4YVJtVnNYWllRSGIvREVDL2p6dGN3VUtWU2E5SEY4bUF4cFBTdnl3QjE4dwpZS2dzNWVocmFWc3ZibUR3MTFhZXo1QWFyTzd5eGpZZ1ZMU3FyM3RGNitjMTU2cjBSZXd3eFN5OXVtTEtSY1JzCjlzNTFFZ0t6VzRGL20vWllELzBEUDVHcEt4RWY0UTFkdERqV3pCOWx6eENSTFdqS1UwelB6RmlhcHVUbFF6VzAKZnYwaFQ1aUxSUHVsdS9wSG50eEIyNEhreXJFSURmQ0V4OWlSaXRucmRzMEZNK1IyakpZQ3dSRDRWcytSQmdRQQo5d0NhS0MrbGRUdExHbU5LbEVRaU5ITFhjc1p0WUhFSE9KTFF0a0tod1VrS0E1OURGWGFJeFdCdmZsa296YkYxCkZ6UjJIcXpMQWdNQkFBRUNnZ0VBQllOV3hzOEZjK2hVemZ6bjk5WXVEYnJ4NmJ3ODROUTRsTmJTaERsMzVnOXkKcWpKbjV1bDBHdWE4VW9yeWpZR01jWWtSa051d0hNa0ZXVmFvQVJGV2ZFdi9OU0pjaHVsaGpyUjY0b3FIaW9HRApmSlpqZWtsUklBbGxTZ1JPZ1ZDK05vbDJaOC9rd2ZUYWcvNkdlNHV2OEszVW9kdzF6aDhXbkpoNnVTREF3clQrCmpLMW1PUlRGQlcycTl0c3FXaE5hNzh3OGdKK0RNc3ZxQmtocXBGelk4WG1LMWw0bXd3N0MvRFhRRTArdWdDTUMKeFoxUlNlUmVQd0RoTlE1U3FpLzN3NEk1UXlsak5GYmMyZEJzOGpxd0wrV1FNTmR2WDBaS3c3Wml2UDN1ZDVaZwprUFFtYldBbk54Z1R0TWVQY0hVZXdWVWcybUFUMEdVSW9QRWNNVjFJb1FLQmdRRDJtRmtVZkx4ZVpESVVJbGFKCjZjRGRCV1JQSU5pK3RBSHpGOXEvdS9xTXl0MmpuelZwdUJxbHJYdm5EV3llRG83OFVJTTFYOCtuK3lob2I5dTcKbkJWSEpldTNBanpLalJ2V1lsM1ljQll6cW5OTHBwMUwySTNoQ2FmTTNnYjNSbk1ubTdsaE9xUlUxazJJWTVtNwpYUHZDYmZtZVlZYWFtWjN3UEwzUk5LVlowUUtCZ1FEWGNiSmFQdHdnamUvY0oxdWViL3NnOUNRUE95bklWWTdICkVWUDNTZzYzQWc5ZDY1NWR6T2NxaHJwdlRITFZyMC9FVXRiMVhDRTR5NGI1R3UxeXZZMkV3Y2VRS2NQTWwyTlEKRXlsd3RPNThhTHpRUTFsVU4yZVRlTmI4TzMzVDdacDZ4dittL3ROWlpLQjdqN3JnenU2OGEyUmNPanpUaEZQcwpkRHZQL3p3bjJ3S0JnUUNBcnhBTmVPcHo5NldLakVETXg0YzF6OUtBMkl0RE9YeXE5dy9ZYnFoWlFLUlk5b1JSCkh4b0l5M2VWSTVSREJ5WG0xYjBpNVZUZ1BGamg1ejJyc2RBSXlPa3hINkhKc2NtTkh0Z0tVclBEVW5mSVNySmIKR2k4ditISHdud3pUalpnYVcxRnFROGZ0M2Nlb0hSSGtqS2wwMVI4bVg0NTJyeU9VY3A0N3hsVmpnUUtCZ0RxSwptbndMT0tWZjdCMVdWSDdvenNSVmtyYlF6TG16QmVqeHZHOGxvSG42QlZMd0EwaFp0VGJKQlQvWTloczZWK0p3CjRCZ3J3SnMrTXA3ZHdrZTdXZ2tJM3NFOW1BYXYzRHlWK0Z5M3pWWGczKzEzWDM2U3o0SXpBN2ZtTW5xenhaWTMKSEtDei9abjh6ZDdGWDNKV3lHaEtoaXJKYUYzUlJ6eXBHTmViOHl5aEFvR0FHcmJ3dGZoV0NZZmtXWldINnZQTApSaXdMRWYxTEdCYzA1YnZsbjlLNXpXZVpTVkNxR3JSeURaVGlqRVZOeHpLYmh0YThyb0tRRmhRTDVWU2JNOHNVCkRXQU5jKzZBb051K00xUnpuRGlhdDRENUhmTi96UExoclZhSWpTOEwzQmtSWkREeWZFWDlEZkprY3NmYlhITXgKTUxBMmhwTUF5aDR0WE93TmJjL3NON2M9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  paths:
    - path: /static
      service: react-app-frontend
      port: 3001
    - path: /user
      service: react-app-backend
      port: 3000

services:
  - name: frontend
    enabled: true
    replicas: 1
    image: ghcr.io/djordjevic-milan/userlist-frontend:latest
    env:
      - name: API_URL
        value: "http://api:3000"
      - name: NODE_ENV
        value: "production"
      - name: REQUESTED_API_URL
        value: "http://backend:3000/api"
    secret: []  # No secrets for frontend
    probes:
      readiness:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 15
        periodSeconds: 20
        failureThreshold: 5

  - name: backend
    enabled: true
    replicas: 1
    image: ghcr.io/djordjevic-milan/userlist-backend:latest
    env:
      - name: DB_HOST
        value: "mysql"
      - name: DB_PORT
        value: "3306"
      - name: DB_NAME
        value: "appdb"
    secret:
      - key: DB_USER
        value: "root"
      - key: DB_PASSWORD
        value: "pass123"
    ## Disabled!!! Liveness probe is possible only when database is already inisialized, but at first start we have to initialaze DB manually from application.
    # probes: 
    #   readiness:
    #     httpGet:
    #       path: /user
    #       port: 3000
    #     initialDelaySeconds: 5
    #     periodSeconds: 10
    #     failureThreshold: 3
    #   liveness:
    #     httpGet:
    #       path: /user
    #       port: 3000
    #     initialDelaySeconds: 15
    #     periodSeconds: 20
    #     failureThreshold: 5
